# Generated by Django 5.0.6 on 2024-06-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees_list',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employees_list',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
